### ISSUE TITLE
forge issues: no funciona "reply", antes era con S-r

### ISSUE THREAD

**Issue by fstafforini** [tlon-team/tlon.el#14]
Recibo este error tratando de hacer reply a un issue en este repo (tlon.el):

```elisp
files--ensure-directory: Creating directory: Read-only file system, /magit [5 times]
```

**Comment by fstafforini** [comment]
Lo hace en el perfil 6.8.1, no puedo probar aún en el 6.8.2

**Comment by benthamite** [comment]
Eso es un bug de Forge. Si le das “reply” habiendo entrado al issue desde la lista de notificaciones, *a veces* no funciona. No termino de entender bién exactamente cuándo ocurre.
