### ISSUE TITLE
Excluir `extras` automáticamente cuando se excuye el paquete asociado

### ISSUE THREAD

**Issue by benthamite** [tlon-team/tlon.el#16]
Continúa tlon-team/tlon.el#12.

**Comment by benthamite** [comment]
@fstafforini , @worldsaround: esto estará implementado a partir de la próxima versión de mi config. Ya no es necesario que agreguen explícitamente los "extras" de los paquetes que excluyen a la lista de exclusiones.

**Comment by fstafforini** [comment]
gracias!
