### ISSUE TITLE
Falla `;` en una entrada bib

### ISSUE THREAD

**Issue by worldsaround** [tlon-team/tlon.el#17]
Es decir, la funcionalidad que dispara un montón de funciones con el punto y coma. El debugger no se dispara, pero el minibuffer muestra el error: eww-extras-url-to-file: Wrong type argument: stringp, nil

**Comment by benthamite** [comment]
La próxima vez que ocurra, fijate si podés encontrar el backtrace. Normalmente, cuando no se dispara el debugger es porque ya hay un buffer con otro backtrace.

**Comment by worldsaround** [comment]
En Benson2023UpdatedOctober7, por ejemplo:

```
Debugger entered--Lisp error: (error "Autoloading file /Users/cartago/.config/emacs-profiles/6.8.2a/elpaca/builds/embark/embark.elc failed to define function citar-extras-open-in-ebib")
  citar-extras-open-in-ebib("Benson2023UpdatedOctober7")
  tlon-deepl-translate-abstract()
  ebib-extras-process-entry()
  funcall-interactively(ebib-extras-process-entry)
  command-execute(ebib-extras-process-entry)
```

**Comment by benthamite** [comment]
Arreglado. Va a estar disponible cuando publique la próxima config. Mientras tanto, podés resolverlo evaluando lo siguiente:

``` emacs-lisp
(defun citar-extras-open-in-ebib (citekey)
  "Open bibliographic entry associated with the CITEKEY in Ebib."
  (interactive (list (citar-select-ref)))
  (unless (get-buffer "*ebib*")
    (ebib))
  (ebib-extras-open-key citekey))
```
